wget https://www.netsurf-browser.org/webimages/nav.png
wget https://www.netsurf-browser.org/webimages/arrow.png
wget https://www.netsurf-browser.org/webimages/arrow.png
wget https://www.netsurf-browser.org/webimages/arrow.png
wget https://www.netsurf-browser.org/webimages/downloadbg.png
wget https://www.netsurf-browser.org/webimages/downloadtl.png
wget https://www.netsurf-browser.org/webimages/downloadtr.png
wget https://www.netsurf-browser.org/webimages/downloadbl.png
wget https://www.netsurf-browser.org/webimages/downloadbr.png
wget https://www.netsurf-browser.org/webimages/downloadarrow.png
wget https://www.netsurf-browser.org/webimages/downloadlogo.png
wget https://www.netsurf-browser.org/webimages/dlriscos.png
wget https://www.netsurf-browser.org/webimages/dlgtk.png
wget https://www.netsurf-browser.org/webimages/dlhaiku.png
wget https://www.netsurf-browser.org/webimages/dlamiga.png
wget https://www.netsurf-browser.org/webimages/dlwindows.png
wget https://www.netsurf-browser.org/webimages/dlatari.png
wget https://www.netsurf-browser.org/webimages/dlsource.png
wget https://www.netsurf-browser.org/webimages/downloadlogo.png
wget https://www.netsurf-browser.org/webimages/source.png
wget https://www.netsurf-browser.org/webimages/netsurf.png
wget https://www.netsurf-browser.org/webimages/downloadarrow.png
wget https://www.netsurf-browser.org/webimages/netsurf.png
wget https://www.netsurf-browser.org/webimages/source.png
wget https://www.netsurf-browser.org/webimages/nstheme.png
wget https://www.netsurf-browser.org/webimages/caution.png
